---
apiVersion: "v1"
data:
  trustdb.gpg: ""
  pubring.gpg: ""
  gpg.conf: ""
  secring.gpg: ""
kind: "Secret"
metadata:
  annotations: {}
  labels: {}
  name: "jenkins-release-gpg"
type: "fabric8.io/jenkins-release-gpg"
