---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "jenkins"
    provider: "fabric8"
    expose: "false"
  name: "jenkins-jnlp"
spec:
  ports:
  - name: "agent"
    port: 50000
    protocol: "TCP"
    targetPort: 50000
  selector:
    app: "jenkins"
    provider: "fabric8"
