---
apiVersion: "v1"
data:
  token: ${RECOMMENDER_API_TOKEN}
kind: "Secret"
metadata:
  annotations: {}
  labels: {}
  name: "jenkins-recommender-api-token"
type: "fabric8.io/jenkins-recommender-api-token"
